### ISSUE TITLE
Request: Short Tutorial

### ISSUE THREAD

**Issue by Welding-Torch** [petargyurov/virtual-bookshelf#2]
Hey man, I found this repo through your post on Reddit. I think it's really great and I wanna add it to my site too. 

My site is a simple jekyll blog. I've only written plain text posts in markdown so far, and I am unsure of how to add this into the 'About' page of my site. How would I go about adding this bookshelf to the 'About' page of my site?

If you could give me some steps to do that, I'd be thankful.

**Comment by petargyurov** [comment]
Hey, I'd be happy to help out.

If you are familiar with Jekyll you might benefit from seeing how I've set it up in my [blog repo](https://github.com/petargyurov/petargyurov.github.io).

I'd have to clone your repo and try to see what's going, but I won't have time to do that right away. Hopefully tomorrow.

--
Side note: did you mean HackerNews instead of Reddit? I haven't posted on Reddit 😕

**Comment by petargyurov** [comment]
I made a [PR](https://github.com/Welding-Torch/welding-torch.github.io/pull/1) to your blog repo to integrate the bookshelf. Let me know if you need any more help.

**Comment by Welding-Torch** [comment]
Hey Peter, sorry for the late reply, I've been busy with college tests. 

Oh wow! Thank you so much for taking a look and helping me out! This is more than what I expected. I have spent some time studying the changes you made in your PR. While I don't understand it fully, I do think I understand the majority. It looks great on my site, and I think I will use this more.

Yeah, I might have found it on HackerNews instead haha, I spend so much time seeing cool links on Reddit that I mix the 2 sometimes.

Once again, thank you for your help.
---

**Comment by Welding-Torch** [comment]
Hey one more thing though, I think there seems to be some problem with linking bookshelf_macro.html to the final product. Because I'm adding more books, but the colours/sizes aren't showing up. It's just giving me a blank spine w/ no colour and books of a same size. Could you take a look?
